/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lil uzoy
 */
public class Pengembalian extends javax.swing.JFrame {
    public Pengembalian() {
        initComponents();
        table_update();
        LoadCategory();
    }
        Connection con;
        PreparedStatement pst = null;
        PreparedStatement pst1 = null;
        PreparedStatement pst2 = null; 
        PreparedStatement pst3 = null; 
        PreparedStatement pst4 = null;
        PreparedStatement pst5 = null;
        ResultSet rs;
        ResultSet rs1;
        ResultSet rs2;
        ResultSet rs3;
        
    public void LoadCategory() {
       try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan_sekolah", "root", "");
            pst4 = con.prepareStatement("SELECT * FROM peminjaman");
            
            rs3 = pst4.executeQuery();
            kode_buku.removeAllItems();
            while (rs3.next()) {
                kode_buku.addItem(rs3.getString(2));
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdl_buku = new javax.swing.JTextField();
        txtpenerbit = new javax.swing.JTextField();
        thnterbit = new javax.swing.JTextField();
        txtfine = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kode_buku = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        batal = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        oke = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txnama_penulis = new javax.swing.JTextField();
        txt_nis = new javax.swing.JTextField();
        txnama_peminjam = new javax.swing.JTextField();
        txtdue = new javax.swing.JTextField();
        txtelp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 620));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Kode Buku");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 90, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Judul Buku");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 60, 70, 30);
        jPanel1.add(jdl_buku);
        jdl_buku.setBounds(110, 60, 270, 30);

        txtpenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpenerbitActionPerformed(evt);
            }
        });
        jPanel1.add(txtpenerbit);
        txtpenerbit.setBounds(110, 140, 270, 30);

        thnterbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thnterbitActionPerformed(evt);
            }
        });
        jPanel1.add(thnterbit);
        thnterbit.setBounds(110, 180, 270, 30);

        txtfine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfineActionPerformed(evt);
            }
        });
        jPanel1.add(txtfine);
        txtfine.setBounds(580, 180, 290, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Penerbit");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 140, 100, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tahun Terbit");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 180, 90, 30);

        kode_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_bukuActionPerformed(evt);
            }
        });
        jPanel1.add(kode_buku);
        kode_buku.setBounds(110, 20, 270, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rp.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 180, 20, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Denda");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(460, 180, 60, 30);

        batal.setBackground(new java.awt.Color(204, 204, 255));
        batal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        batal.setText("Batal");
        batal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel1.add(batal);
        batal.setBounds(110, 270, 91, 40);

        kembali.setBackground(new java.awt.Color(204, 204, 255));
        kembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kembali.setText("Kembali");
        kembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali);
        kembali.setBounds(208, 270, 90, 40);

        oke.setBackground(new java.awt.Color(204, 204, 255));
        oke.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        oke.setText("Ok");
        oke.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        oke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okeActionPerformed(evt);
            }
        });
        jPanel1.add(oke);
        oke.setBounds(10, 270, 91, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Penulis");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 100, 90, 30);
        jPanel1.add(txnama_penulis);
        txnama_penulis.setBounds(110, 100, 270, 30);
        jPanel1.add(txt_nis);
        txt_nis.setBounds(580, 20, 290, 30);
        jPanel1.add(txnama_peminjam);
        txnama_peminjam.setBounds(580, 60, 290, 30);

        txtdue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdueActionPerformed(evt);
            }
        });
        jPanel1.add(txtdue);
        txtdue.setBounds(580, 100, 290, 30);

        txtelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtelpActionPerformed(evt);
            }
        });
        jPanel1.add(txtelp);
        txtelp.setBounds(580, 140, 290, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NIS");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(460, 20, 70, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama Peminjam");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(460, 60, 90, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tanggal Kembali");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(460, 100, 100, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Terlambat/hari");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(460, 140, 90, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Buku", "Judul Buku", "Penulis", "Penerbit", "Tahun Terbit", "NIS", "Nama Peminjam", "Tanggal Kembali", "Keterlambatan", "Denda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 340, 910, 230);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pengembalian_buku.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, -50, 950, 670);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 950, 620);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Pengembalian Buku Pinjam");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 10, 330, 29);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void table_update() {
        int CC;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan_sekolah","root","");
            pst1 = con.prepareStatement("SELECT * FROM pengembalian_buku");
            ResultSet Rs = pst1.executeQuery();
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
            DFT.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();
                for (int ii = 1; ii <= CC; ii++) {
                    v2.add(Rs.getString("kode_buku"));
                    v2.add(Rs.getString("judul_buku"));
                    v2.add(Rs.getString("penulis"));
                    v2.add(Rs.getString("penerbit"));
                    v2.add(Rs.getString("tahun_terbit"));
                    v2.add(Rs.getString("nis"));
                    v2.add(Rs.getString("nama_peminjam"));
                    v2.add(Rs.getString("return_date"));
                    v2.add(Rs.getString("elp"));
                    v2.add(Rs.getString("fine"));
                }
                DFT.addRow(v2);
            }
        } catch (Exception e) {
        }
    }  
    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        kode_buku.setSelectedIndex(0);
        jdl_buku.setText("");
        txnama_penulis.setText("");
        txtpenerbit.setText("");
        thnterbit.setText("");
        txt_nis.setText("");
        txnama_peminjam.setText("");
        txtdue.setText("");
        txtelp.setText("");
        txtfine.setText("");
    }//GEN-LAST:event_batalActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
         Main m = new Main();
            this.hide();
            m.setVisible(true);
    }//GEN-LAST:event_kembaliActionPerformed

    private void thnterbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thnterbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thnterbitActionPerformed

    private void txtfineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfineActionPerformed

    private void okeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okeActionPerformed
        // TODO add your handling code here:
        try {
            String kode = kode_buku.getSelectedItem().toString();
            String judul = jdl_buku.getText();
            String npenulis = txnama_penulis.getText();
            String npenerbit = txtpenerbit.getText();
            String thnterbits = thnterbit.getText();
            String nis = txt_nis.getText();
            String npeminjam = txnama_peminjam.getText();
            String duedate = txtdue.getText();
            String elped = txtelp.getText();
            String fines = txtfine.getText();
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan_sekolah", "root", "");
            
            pst3 = con.prepareStatement("insert into pengembalian_buku (kode_buku,judul_buku,penulis,penerbit,tahun_terbit,nis,nama_peminjam,return_date,elp,fine)values(?,?,?,?,?,?,?,?,?,?)");
            pst3.setString(1,kode);
            pst3.setString(2,judul);
            pst3.setString(3,npenulis);
            pst3.setString(4,npenerbit); 
            pst3.setString(5,thnterbits); 
            pst3.setString(6,nis); 
            pst3.setString(7,npeminjam);
            pst3.setString(8,duedate);
            pst3.setString(9,elped);
            pst3.setString(10,fines);
            pst3.executeUpdate();
            
            pst = con.prepareStatement("update daftar_buku set status = 'Tersedia' where kode_buku = ?  ");
            pst.setString(1, kode);
            pst.executeUpdate();
            
            pst2 = con.prepareStatement("Delete from peminjaman where kode_buku = ?  ");
            pst2.setString(1, kode);
            pst2.executeUpdate();            
            
            JOptionPane.showMessageDialog(this, "Data Diperbaharui!");
        }catch (ClassNotFoundException ex){
            Logger.getLogger(Peminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex){
            Logger.getLogger(Peminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_okeActionPerformed

    private void kode_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_bukuActionPerformed
        // TODO add your handling code here:
        try{
            String nobuk = kode_buku.getSelectedItem().toString();
                    
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/perpustakaan_sekolah", "root", "");
            pst5 = con.prepareStatement("select judul_buku,penulis,penerbit,tahun_terbit,nis,nama_peminjam,due,total_hari,DATEDIFF(NOW(),due) as elap from peminjaman where kode_buku = ? ");
            pst5.setString(1, nobuk);
            rs2 = pst5.executeQuery();
            if (rs2.next() == false){
                JOptionPane.showMessageDialog(null, "Data Tidak Tersedia");
            }else{
                String juduls = rs2.getString("judul_buku");
                jdl_buku.setText(juduls.trim());
                
                String pnuliz = rs2.getString("penulis");
                txnama_penulis.setText(pnuliz.trim());
                
                String pnerbid = rs2.getString("penerbit");
                txtpenerbit.setText(pnerbid.trim());
                
                String thntrbit = rs2.getString("tahun_terbit");
                thnterbit.setText(thntrbit.trim());
                
                String niss = rs2.getString("nis");
                txt_nis.setText(niss.trim());
                
                String nama = rs2.getString("nama_peminjam");
                txnama_peminjam.setText(nama.trim());
                
                String tgl_kml = rs2.getString("due");
                txtdue.setText(tgl_kml.trim());
                
                String elp = rs2.getString("elap");
                int elaped = Integer.parseInt(elp);
                  if(elaped>0){
                    txtelp.setText(elp);
                    int fine = elaped * 5000;
                    txtfine.setText(String.valueOf(fine));
                  }else{
                    txtelp.setText("0");
                    txtfine.setText("0");
                  }
            }
           
        }catch (ClassNotFoundException ex){
            Logger.getLogger(AnggotaPerpustakaan.class.getName()).log(Level.SEVERE, null, ex);
        }catch(SQLException ex){
            Logger.getLogger(AnggotaPerpustakaan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kode_bukuActionPerformed

    private void txtpenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenerbitActionPerformed

    private void txtdueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdueActionPerformed

    private void txtelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jdl_buku;
    private javax.swing.JButton kembali;
    private javax.swing.JComboBox<String> kode_buku;
    private javax.swing.JButton oke;
    private javax.swing.JTextField thnterbit;
    private javax.swing.JTextField txnama_peminjam;
    private javax.swing.JTextField txnama_penulis;
    private javax.swing.JTextField txt_nis;
    private javax.swing.JTextField txtdue;
    private javax.swing.JTextField txtelp;
    private javax.swing.JTextField txtfine;
    private javax.swing.JTextField txtpenerbit;
    // End of variables declaration//GEN-END:variables
}
